# src/main/resources/application.yml

spring:
  # Sets the default profile to 'dev' if none is explicitly specified (e.g., via command line)
  profiles:
    active: dev

server:
  port: 8080 # Default port for the API

logging:
  level:
    root: INFO
    # Set logging for our application package
    com.threatbeacon: DEBUG